### ISSUE TITLE
[Bug]: Can't use subfolders

### ISSUE THREAD

**Issue by AnimeniacYuuto** [Fuzss/forgeconfigapiport-fabric#15] opened 2022-08-16 06:44 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.2.3

### Notes (Required)

The library fails and crashes when trying to put config files in subfolders, this works on fine on forge so was hoping to get it working on fabric/quilt as well.

**Comment by Fuzss** [comment] 2022-08-16 08:10
Do you have a crash-log for me?

**Comment by AnimeniacYuuto** [comment] 2022-08-16 08:58
https://pastebin.com/dGG2FvNF there is the crash log I've been getting,

**Comment by Fuzss** [comment] 2022-08-17 21:38
Ah I remember this now. The problem is the directory doesn't exist. Forge didn't create intermediary directories automatically until recently, so I'm still missing that change.

For now just make sure the directory is manually created before creating the config.

**Comment by Fuzss** [comment] 2022-08-21 21:15
Fixed now in latest version.

**Closed by Fuzss** 2022-08-21 21:15 UTC
Labels: bug
